### ISSUE TITLE
This's mine!

### ISSUE THREAD

**Issue by jasonliao** [DrakeLeung/lamb-moji#1]
![](http://ww4.sinaimg.cn/large/7988751agw1f6fozxg4omj20k3039t8p.jpg)

Like a :monkey_face:  waiting for the :traffic_light:  (That monkey is one of the few emojis that ubuntu can display :joy: )

**Comment by lyyourc** [comment]
Ha-ha-ha
It proves that we are in the same channel ~

**Comment by jasonliao** [comment]
Cheers! :beers:
